In [1]:
import nltk

In [6]:
text = """1. Chocolate Chip Cookies: Combine 2 cups of flour, 1 cup of sugar, 1 cup of brown sugar, 1 tsp of baking soda, and a pinch of salt. Cream together with 1 cup of softened butter, add 2 eggs and 2 tsp of vanilla extract. Fold in 2 cups of chocolate chips. Drop spoonfuls on a baking sheet and bake at 350°F for 10 minutes until golden brown.
2. Vegetable Stir Fry: Heat 2 tbsp of olive oil in a pan, add minced garlic and 1 inch of grated ginger, then add sliced vegetables like broccoli, carrots, and bell peppers. Stir-fry until tender. Add 2 tbsp of soy sauce and serve hot with rice or noodles.
3. Banana Bread: Mash 3 ripe bananas, mix with 1/3 cup melted butter. Stir in 1 cup of sugar, 1 beaten egg, and 1 tsp of vanilla extract. Mix in 1 tsp of baking soda and a pinch of salt. Gently fold in 1.5 cups of flour. Pour into a loaf pan and bake at 350°F for 1 hour.
4. Chicken Curry: Sauté 1 chopped onion, 2 minced garlic cloves, and 1 tbsp of grated ginger in a pan with oil. Add 1 lb of diced chicken breast, cook until browned. Stir in 2 tsp of curry powder, add 1 can of crushed tomatoes, and 1 cup of coconut milk. Simmer for 20 minutes. Serve with rice.
5. Spaghetti Carbonara: Cook 8 oz of spaghetti according to package instructions. In a separate pan, cook 4 slices of chopped bacon until crisp. Beat 2 eggs and 1/2 cup of grated Parmesan cheese together, mix with hot, drained spaghetti, add bacon, and season with black pepper.
6. Caesar Salad: Toss 4 cups of chopped romaine lettuce with Caesar dressing. Add croutons and sprinkle with grated Parmesan cheese. For added protein, top with grilled chicken strips.
7. Beef Tacos: Cook 1 lb of ground beef with taco seasoning. Serve in tortillas with toppings like lettuce, diced tomatoes, shredded cheese, and sour cream.
8. Margarita Pizza: Spread tomato sauce over a round of pizza dough, sprinkle with 8 oz of shredded mozzarella cheese, add fresh basil leaves. Bake at 475°F for 10-12 minutes. Drizzle with olive oil before serving.
9. Lemonade: Mix 1 cup of lemon juice with 1 cup of sugar and 4 cups of water. Adjust sweetness by adding more sugar or water if necessary. Serve over ice.
10. French Toast: Whisk together 2 eggs, 1/2 cup of milk, a pinch of cinnamon, and 1 tsp of vanilla extract. Dip slices of bread into the mixture, fry in a buttered pan until golden on both sides. Serve with maple syrup.
11. Guacamole: Mash 2 ripe avocados in a bowl, mix with the juice of 1 lime, salt to taste, 1/4 cup of minced onion, 1 diced tomato, 1 minced garlic clove, and chopped cilantro.
12. Pumpkin Soup: Sauté 1 chopped onion and 2 minced garlic cloves in a pot with olive oil. Add 2 cups of pumpkin puree, 4 cups of vegetable stock, simmer for 20 minutes. Blend until smooth, stir in 1/2 cup of cream, season with salt and pepper.
13. Raspberry Smoothie: Blend 1 cup of raspberries, 1 sliced banana, 1/2 cup of yogurt, 1 tbsp of honey, and a handful of ice until smooth.
14. Macaroni and Cheese: Cook 8 oz of macaroni. In a saucepan, melt 2 tbsp of butter, stir in 2 tbsp of flour, gradually add 2 cups of milk, stirring until thickened. Add 2 cups of shredded cheddar cheese, stir until melted. Combine with macaroni, transfer to a baking dish, top with breadcrumbs, and bake at 350°F for 20 minutes.
15. Chicken Alfredo Pasta: Cook 8 oz of fettuccine, drain. In a pan, cook 1 lb of sliced chicken breast until golden. Add 1 cup of Alfredo sauce to the chicken, heat through. Toss with pasta, garnish with grated Parmesan cheese.
16. Mushroom Risotto: In a saucepan, sauté 1 cup of chopped mushrooms and 1/2 cup of chopped onion in butter until soft. Stir in 1 cup of Arborio rice, cook until translucent. Gradually add 4 cups of vegetable broth, stirring constantly, until the rice is creamy and tender. Finish with grated Parmesan cheese and a drizzle of truffle oil.
17. Tomato Bruschetta: Dice 2 large tomatoes and mix with 1/4 cup of finely chopped basil, 2 minced garlic cloves, 1 tbsp olive oil, 1 tsp balsamic vinegar, salt, and pepper to taste. Spoon onto slices of toasted baguette.
18. Grilled Salmon: Marinate 4 salmon fillets in a mixture of olive oil, lemon juice, minced garlic, salt, and pepper for at least 30 minutes. Grill over medium heat for 3-4 minutes per side or until desired doneness.
19. Chicken Parmesan: Pound 4 chicken breasts to even thickness. Dip in beaten eggs, then in a mixture of breadcrumbs and grated Parmesan. Fry until golden, place in a baking dish, cover with marinara sauce and mozzarella cheese. Bake at 375°F for 20 minutes.
20. Vegetable Quiche: Pre-bake a pie crust at 375°F for 10 minutes. Sauté 1 cup each of chopped spinach, mushrooms, and onions until soft. Spread the vegetables in the crust, pour over a mixture of 4 beaten eggs and 1 cup of cream. Top with 1/2 cup of shredded cheese. Bake at 375°F for 35 minutes."""

In [14]:
recipes = {"Dish":[],"Recipe":[]}
for recipe in text.split('\n'):
    recipes["Dish"].append(recipe.split(':')[0].split('.')[1].strip())
    recipes["Recipe"].append(recipe.split(':')[1])

In [15]:
recipes

{'Dish': ['Chocolate Chip Cookies',
  'Vegetable Stir Fry',
  'Banana Bread',
  'Chicken Curry',
  'Spaghetti Carbonara',
  'Caesar Salad',
  'Beef Tacos',
  'Margarita Pizza',
  'Lemonade',
  'French Toast',
  'Guacamole',
  'Pumpkin Soup',
  'Raspberry Smoothie',
  'Macaroni and Cheese',
  'Chicken Alfredo Pasta',
  'Mushroom Risotto',
  'Tomato Bruschetta',
  'Grilled Salmon',
  'Chicken Parmesan',
  'Vegetable Quiche'],
 'Recipe': [' Combine 2 cups of flour, 1 cup of sugar, 1 cup of brown sugar, 1 tsp of baking soda, and a pinch of salt. Cream together with 1 cup of softened butter, add 2 eggs and 2 tsp of vanilla extract. Fold in 2 cups of chocolate chips. Drop spoonfuls on a baking sheet and bake at 350°F for 10 minutes until golden brown.',
  ' Heat 2 tbsp of olive oil in a pan, add minced garlic and 1 inch of grated ginger, then add sliced vegetables like broccoli, carrots, and bell peppers. Stir-fry until tender. Add 2 tbsp of soy sauce and serve hot with rice or noodles.',
  ' Mash 3 ripe bananas, mix with 1/3 cup melted butter. Stir in 1 cup of sugar, 1 beaten egg, and 1 tsp of vanilla extract. Mix in 1 tsp of baking soda and a pinch of salt. Gently fold in 1.5 cups of flour. Pour into a loaf pan and bake at 350°F for 1 hour.',
  ' Sauté 1 chopped onion, 2 minced garlic cloves, and 1 tbsp of grated ginger in a pan with oil. Add 1 lb of diced chicken breast, cook until browned. Stir in 2 tsp of curry powder, add 1 can of crushed tomatoes, and 1 cup of coconut milk. Simmer for 20 minutes. Serve with rice.',
  ' Cook 8 oz of spaghetti according to package instructions. In a separate pan, cook 4 slices of chopped bacon until crisp. Beat 2 eggs and 1/2 cup of grated Parmesan cheese together, mix with hot, drained spaghetti, add bacon, and season with black pepper.',
  ' Toss 4 cups of chopped romaine lettuce with Caesar dressing. Add croutons and sprinkle with grated Parmesan cheese. For added protein, top with grilled chicken strips.',
  ' Cook 1 lb of ground beef with taco seasoning. Serve in tortillas with toppings like lettuce, diced tomatoes, shredded cheese, and sour cream.',
  ' Spread tomato sauce over a round of pizza dough, sprinkle with 8 oz of shredded mozzarella cheese, add fresh basil leaves. Bake at 475°F for 10-12 minutes. Drizzle with olive oil before serving.',
  ' Mix 1 cup of lemon juice with 1 cup of sugar and 4 cups of water. Adjust sweetness by adding more sugar or water if necessary. Serve over ice.',
  ' Whisk together 2 eggs, 1/2 cup of milk, a pinch of cinnamon, and 1 tsp of vanilla extract. Dip slices of bread into the mixture, fry in a buttered pan until golden on both sides. Serve with maple syrup.',
  ' Mash 2 ripe avocados in a bowl, mix with the juice of 1 lime, salt to taste, 1/4 cup of minced onion, 1 diced tomato, 1 minced garlic clove, and chopped cilantro.',
  ' Sauté 1 chopped onion and 2 minced garlic cloves in a pot with olive oil. Add 2 cups of pumpkin puree, 4 cups of vegetable stock, simmer for 20 minutes. Blend until smooth, stir in 1/2 cup of cream, season with salt and pepper.',
  ' Blend 1 cup of raspberries, 1 sliced banana, 1/2 cup of yogurt, 1 tbsp of honey, and a handful of ice until smooth.',
  ' Cook 8 oz of macaroni. In a saucepan, melt 2 tbsp of butter, stir in 2 tbsp of flour, gradually add 2 cups of milk, stirring until thickened. Add 2 cups of shredded cheddar cheese, stir until melted. Combine with macaroni, transfer to a baking dish, top with breadcrumbs, and bake at 350°F for 20 minutes.',
  ' Cook 8 oz of fettuccine, drain. In a pan, cook 1 lb of sliced chicken breast until golden. Add 1 cup of Alfredo sauce to the chicken, heat through. Toss with pasta, garnish with grated Parmesan cheese.',
  ' In a saucepan, sauté 1 cup of chopped mushrooms and 1/2 cup of chopped onion in butter until soft. Stir in 1 cup of Arborio rice, cook until translucent. Gradually add 4 cups of vegetable broth, stirring constantly, until the rice is creamy and tender. Finish with grated Parmesan cheese and a drizzle of truffle oil.',
  ' Dice 2 large tomatoes and mix with 1/4 cup of finely chopped basil, 2 minced garlic cloves, 1 tbsp olive oil, 1 tsp balsamic vinegar, salt, and pepper to taste. Spoon onto slices of toasted baguette.',
  ' Marinate 4 salmon fillets in a mixture of olive oil, lemon juice, minced garlic, salt, and pepper for at least 30 minutes. Grill over medium heat for 3-4 minutes per side or until desired doneness.',
  ' Pound 4 chicken breasts to even thickness. Dip in beaten eggs, then in a mixture of breadcrumbs and grated Parmesan. Fry until golden, place in a baking dish, cover with marinara sauce and mozzarella cheese. Bake at 375°F for 20 minutes.',
  ' Pre-bake a pie crust at 375°F for 10 minutes. Sauté 1 cup each of chopped spinach, mushrooms, and onions until soft. Spread the vegetables in the crust, pour over a mixture of 4 beaten eggs and 1 cup of cream. Top with 1/2 cup of shredded cheese. Bake at 375°F for 35 minutes.']}

In [16]:
import pandas as pd

In [18]:
df = pd.DataFrame(recipes)

In [19]:
df

                      Dish                                             Recipe
0   Chocolate Chip Cookies   Combine 2 cups of flour, 1 cup of sugar, 1 cu...
1       Vegetable Stir Fry   Heat 2 tbsp of olive oil in a pan, add minced...
2             Banana Bread   Mash 3 ripe bananas, mix with 1/3 cup melted ...
3            Chicken Curry   Sauté 1 chopped onion, 2 minced garlic cloves...
4      Spaghetti Carbonara   Cook 8 oz of spaghetti according to package i...
5             Caesar Salad   Toss 4 cups of chopped romaine lettuce with C...
6               Beef Tacos   Cook 1 lb of ground beef with taco seasoning....
7          Margarita Pizza   Spread tomato sauce over a round of pizza dou...
8                 Lemonade   Mix 1 cup of lemon juice with 1 cup of sugar ...
9             French Toast   Whisk together 2 eggs, 1/2 cup of milk, a pin...
10               Guacamole   Mash 2 ripe avocados in a bowl, mix with the ...
11            Pumpkin Soup   Sauté 1 chopped onion and 2 minced garlic clo...
12      Raspberry Smoothie   Blend 1 cup of raspberries, 1 sliced banana, ...
13     Macaroni and Cheese   Cook 8 oz of macaroni. In a saucepan, melt 2 ...
14   Chicken Alfredo Pasta   Cook 8 oz of fettuccine, drain. In a pan, coo...
15        Mushroom Risotto   In a saucepan, sauté 1 cup of chopped mushroo...
16       Tomato Bruschetta   Dice 2 large tomatoes and mix with 1/4 cup of...
17          Grilled Salmon   Marinate 4 salmon fillets in a mixture of oli...
18        Chicken Parmesan   Pound 4 chicken breasts to even thickness. Di...
19        Vegetable Quiche   Pre-bake a pie crust at 375°F for 10 minutes....

In [22]:
df["Recipe"][0].strip()

'Combine 2 cups of flour, 1 cup of sugar, 1 cup of brown sugar, 1 tsp of baking soda, and a pinch of salt. Cream together with 1 cup of softened butter, add 2 eggs and 2 tsp of vanilla extract. Fold in 2 cups of chocolate chips. Drop spoonfuls on a baking sheet and bake at 350°F for 10 minutes until golden brown.'

In [23]:
from nltk.tokenize import sent_tokenize

In [24]:
sen = df["Recipe"][0].strip()
sentences = sent_tokenize(sen)
print("Sentence Tokenization:", sentences)

Sentence Tokenization: ['Combine 2 cups of flour, 1 cup of sugar, 1 cup of brown sugar, 1 tsp of baking soda, and a pinch of salt.', 'Cream together with 1 cup of softened butter, add 2 eggs and 2 tsp of vanilla extract.', 'Fold in 2 cups of chocolate chips.', 'Drop spoonfuls on a baking sheet and bake at 350°F for 10 minutes until golden brown.']

In [25]:
from nltk import pos_tag
from nltk.tokenize import word_tokenize

In [26]:
sentence = sentences[0]
words = word_tokenize(sentence)

pos_tags = pos_tag(words)
print("POS Tagging:", pos_tags)

POS Tagging: [('Combine', 'NNP'), ('2', 'CD'), ('cups', 'NNS'), ('of', 'IN'), ('flour', 'NN'), (',', ','), ('1', 'CD'), ('cup', 'NN'), ('of', 'IN'), ('sugar', 'NN'), (',', ','), ('1', 'CD'), ('cup', 'NN'), ('of', 'IN'), ('brown', 'JJ'), ('sugar', 'NN'), (',', ','), ('1', 'CD'), ('tsp', 'NN'), ('of', 'IN'), ('baking', 'VBG'), ('soda', 'NN'), (',', ','), ('and', 'CC'), ('a', 'DT'), ('pinch', 'NN'), ('of', 'IN'), ('salt', 'NN'), ('.', '.')]

In [68]:
final = {}
def fun(x):
    data = {"Amount":[],"Measure Type":[],"Ingredient":[],"Instruction":[],"Step":[]}
    measure_types = ['cups','cup','tsp','pinch','tbsp','minutes','lb','oz','syrup','pan','spoonfuls']
    sentences = sent_tokenize(x[1])
    for i in range(len(sentences)):
        df2 = {"Amount":[],"Measure Type":[],"Ingredient":[],"Instruction":[],"Step":[]}
        df2["Step"] = sentences[i]
        words = word_tokenize(sentences[i])
        pos_tags = pos_tag(words)
        for w,t in pos_tags:
            if t=='NNP':
                df2["Instruction"].append(w)
            elif t=='CD':
                df2["Amount"].append(w)
            elif t=='NNS' or t=='NN':
                if w in measure_types:
                    df2["Measure Type"].append(w)
                else:
                    df2["Ingredient"].append(w)
        data["Amount"].append(df2["Amount"])
        data["Measure Type"].append(df2["Measure Type"])
        data["Ingredient"].append(df2["Ingredient"])
        data["Instruction"].append(df2["Instruction"])
        data["Step"].append(df2["Step"])
    final[x[0]] = data

In [69]:
pd.DataFrame(data)

,Amount,Measure Type,Ingredient,Instruction,Step
0,"[2, 1, 1, 1]","[cups, cup, cup, tsp, pinch]","[flour, sugar, sugar, soda, salt]",[Combine],"Combine 2 cups of flour, 1 cup of sugar, 1 cup..."
1,"[1, 2, 2]","[cup, tsp]","[Cream, butter, eggs, vanilla, extract]",[],"Cream together with 1 cup of softened butter, ..."
2,[2],[cups],"[chocolate, chips]",[Fold],Fold in 2 cups of chocolate chips.
3,"[350°F, 10]",[],"[spoonfuls, sheet, bake, minutes, brown]",[Drop],Drop spoonfuls on a baking sheet and bake at 3...

In [70]:
df.apply(fun,axis=1)

/var/folders/p5/g1xglqt57k33nv_q0c54zcm80000gn/T/ipykernel_1109/765846499.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  sentences = sent_tokenize(x[1])
/var/folders/p5/g1xglqt57k33nv_q0c54zcm80000gn/T/ipykernel_1109/765846499.py:26: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  final[x[0]] = data

0     None
1     None
2     None
3     None
4     None
5     None
6     None
7     None
8     None
9     None
10    None
11    None
12    None
13    None
14    None
15    None
16    None
17    None
18    None
19    None
dtype: object

In [71]:
final

{'Chocolate Chip Cookies': {'Amount': [['2', '1', '1', '1'],
   ['1', '2', '2'],
   ['2'],
   ['350°F', '10']],
  'Measure Type': [['cups', 'cup', 'cup', 'tsp', 'pinch'],
   ['cup', 'tsp'],
   ['cups'],
   ['spoonfuls', 'minutes']],
  'Ingredient': [['flour', 'sugar', 'sugar', 'soda', 'salt'],
   ['Cream', 'butter', 'eggs', 'vanilla', 'extract'],
   ['chocolate', 'chips'],
   ['sheet', 'bake', 'brown']],
  'Instruction': [['Combine'], [], ['Fold'], ['Drop']],
  'Step': [' Combine 2 cups of flour, 1 cup of sugar, 1 cup of brown sugar, 1 tsp of baking soda, and a pinch of salt.',
   'Cream together with 1 cup of softened butter, add 2 eggs and 2 tsp of vanilla extract.',
   'Fold in 2 cups of chocolate chips.',
   'Drop spoonfuls on a baking sheet and bake at 350°F for 10 minutes until golden brown.']},
 'Vegetable Stir Fry': {'Amount': [['2', '1'], [], ['2']],
  'Measure Type': [['tbsp', 'pan'], [], ['tbsp']],
  'Ingredient': [['oil',
    'inch',
    'ginger',
    'vegetables',
    'broccoli',
    'carrots',
    'bell',
    'peppers'],
   ['tender'],
   ['soy', 'sauce', 'rice', 'noodles']],
  'Instruction': [['Heat'], ['Stir-fry'], []],
  'Step': [' Heat 2 tbsp of olive oil in a pan, add minced garlic and 1 inch of grated ginger, then add sliced vegetables like broccoli, carrots, and bell peppers.',
   'Stir-fry until tender.',
   'Add 2 tbsp of soy sauce and serve hot with rice or noodles.']},
 'Banana Bread': {'Amount': [['3', '1/3'],
   ['1', '1', '1'],
   ['1'],
   ['1.5'],
   ['350°F', '1']],
  'Measure Type': [['cup'],
   ['cup', 'tsp'],
   ['tsp', 'pinch'],
   ['cups'],
   ['pan']],
  'Ingredient': [['ripe', 'bananas', 'mix', 'butter'],
   ['sugar', 'beaten', 'egg', 'vanilla', 'extract'],
   ['soda', 'salt'],
   ['flour'],
   ['bake', 'hour']],
  'Instruction': [['Mash'], ['Stir'], ['Mix'], [], ['Pour']],
  'Step': [' Mash 3 ripe bananas, mix with 1/3 cup melted butter.',
   'Stir in 1 cup of sugar, 1 beaten egg, and 1 tsp of vanilla extract.',
   'Mix in 1 tsp of baking soda and a pinch of salt.',
   'Gently fold in 1.5 cups of flour.',
   'Pour into a loaf pan and bake at 350°F for 1 hour.']},
 'Chicken Curry': {'Amount': [['1', '2', '1'],
   ['1'],
   ['2', '1', '1'],
   ['20'],
   []],
  'Measure Type': [['tbsp', 'pan'], ['lb'], ['tsp', 'cup'], ['minutes'], []],
  'Ingredient': [['onion', 'cloves', 'ginger', 'oil'],
   ['chicken', 'breast', 'cook'],
   ['curry', 'powder', 'tomatoes', 'coconut', 'milk'],
   [],
   ['Serve', 'rice']],
  'Instruction': [['Sauté'], [], ['Stir'], ['Simmer'], []],
  'Step': [' Sauté 1 chopped onion, 2 minced garlic cloves, and 1 tbsp of grated ginger in a pan with oil.',
   'Add 1 lb of diced chicken breast, cook until browned.',
   'Stir in 2 tsp of curry powder, add 1 can of crushed tomatoes, and 1 cup of coconut milk.',
   'Simmer for 20 minutes.',
   'Serve with rice.']},
 'Spaghetti Carbonara': {'Amount': [['8'], ['4'], ['2', '1/2']],
  'Measure Type': [['oz'], ['pan'], ['cup']],
  'Ingredient': [['spaghetti', 'package', 'instructions'],
   ['slices', 'bacon', 'crisp'],
   ['eggs', 'cheese', 'mix', 'spaghetti', 'bacon', 'season', 'pepper']],
  'Instruction': [['Cook'], [], ['Beat', 'Parmesan']],
  'Step': [' Cook 8 oz of spaghetti according to package instructions.',
   'In a separate pan, cook 4 slices of chopped bacon until crisp.',
   'Beat 2 eggs and 1/2 cup of grated Parmesan cheese together, mix with hot, drained spaghetti, add bacon, and season with black pepper.']},
 'Caesar Salad': {'Amount': [['4'], [], []],
  'Measure Type': [['cups'], [], []],
  'Ingredient': [['romaine', 'lettuce'],
   ['croutons', 'sprinkle', 'cheese'],
   ['protein', 'top', 'chicken', 'strips']],
  'Instruction': [['Caesar'], ['Add', 'Parmesan'], []],
  'Step': [' Toss 4 cups of chopped romaine lettuce with Caesar dressing.',
   'Add croutons and sprinkle with grated Parmesan cheese.',
   'For added protein, top with grilled chicken strips.']},
 'Beef Tacos': {'Amount': [['1'], []],
  'Measure Type': [['lb'], []],
  'Ingredient': [['ground', 'beef', 'taco', 'seasoning'],
   ['tortillas', 'toppings', 'lettuce', 'tomatoes', 'cheese', 'cream']],
  'Instruction': [['Cook'], ['Serve']],
  'Step': [' Cook 1 lb of ground beef with taco seasoning.',
   'Serve in tortillas with toppings like lettuce, diced tomatoes, shredded cheese, and sour cream.']},
 'Margarita Pizza': {'Amount': [['8'], ['475°F'], []],
  'Measure Type': [['oz'], ['minutes'], []],
  'Ingredient': [['tomato',
    'sauce',
    'round',
    'pizza',
    'dough',
    'sprinkle',
    'mozzarella',
    'cheese',
    'basil',
    'leaves'],
   [],
   ['oil', 'serving']],
  'Instruction': [['Spread'], ['Bake'], ['Drizzle']],
  'Step': [' Spread tomato sauce over a round of pizza dough, sprinkle with 8 oz of shredded mozzarella cheese, add fresh basil leaves.',
   'Bake at 475°F for 10-12 minutes.',
   'Drizzle with olive oil before serving.']},
 'Lemonade': {'Amount': [['1', '1', '4'], [], []],
  'Measure Type': [['cup', 'cup', 'cups'], [], []],
  'Ingredient': [['juice', 'sugar', 'water'],
   ['sweetness', 'sugar', 'water'],
   ['ice']],
  'Instruction': [['Mix'], ['Adjust'], ['Serve']],
  'Step': [' Mix 1 cup of lemon juice with 1 cup of sugar and 4 cups of water.',
   'Adjust sweetness by adding more sugar or water if necessary.',
   'Serve over ice.']},
 'French Toast': {'Amount': [['2', '1/2', '1'], [], []],
  'Measure Type': [['cup', 'pinch', 'tsp'], ['pan'], ['syrup']],
  'Ingredient': [['eggs', 'milk', 'cinnamon', 'vanilla', 'extract'],
   ['slices', 'bread', 'mixture', 'fry', 'sides'],
   ['Serve']],
  'Instruction': [['Whisk'], ['Dip'], []],
  'Step': [' Whisk together 2 eggs, 1/2 cup of milk, a pinch of cinnamon, and 1 tsp of vanilla extract.',
   'Dip slices of bread into the mixture, fry in a buttered pan until golden on both sides.',
   'Serve with maple syrup.']},
 'Guacamole': {'Amount': [['2', '1', '1/4', '1', '1']],
  'Measure Type': [['cup']],
  'Ingredient': [['ripe',
    'avocados',
    'bowl',
    'mix',
    'juice',
    'lime',
    'salt',
    'onion',
    'tomato',
    'clove',
    'cilantro']],
  'Instruction': [['Mash']],
  'Step': [' Mash 2 ripe avocados in a bowl, mix with the juice of 1 lime, salt to taste, 1/4 cup of minced onion, 1 diced tomato, 1 minced garlic clove, and chopped cilantro.']},
 'Pumpkin Soup': {'Amount': [['1', '2'], ['2', '4', '20'], ['1/2']],
  'Measure Type': [[], ['cups', 'cups', 'minutes'], ['cup']],
  'Ingredient': [['onion', 'cloves', 'pot', 'oil'],
   ['puree', 'stock', 'simmer'],
   ['stir', 'cream', 'season', 'salt', 'pepper']],
  'Instruction': [['Sauté'], [], ['Blend', 'smooth']],
  'Step': [' Sauté 1 chopped onion and 2 minced garlic cloves in a pot with olive oil.',
   'Add 2 cups of pumpkin puree, 4 cups of vegetable stock, simmer for 20 minutes.',
   'Blend until smooth, stir in 1/2 cup of cream, season with salt and pepper.']},
 'Raspberry Smoothie': {'Amount': [['1', '1', '1/2', '1']],
  'Measure Type': [['cup', 'cup', 'tbsp']],
  'Ingredient': [['raspberries',
    'banana',
    'yogurt',
    'honey',
    'handful',
    'ice',
    'smooth']],
  'Instruction': [['Blend']],
  'Step': [' Blend 1 cup of raspberries, 1 sliced banana, 1/2 cup of yogurt, 1 tbsp of honey, and a handful of ice until smooth.']},
 'Macaroni and Cheese': {'Amount': [['8'],
   ['2', '2', '2'],
   ['2'],
   ['350°F', '20']],
  'Measure Type': [['oz'], ['tbsp', 'tbsp', 'cups'], ['cups'], ['minutes']],
  'Ingredient': [['macaroni'],
   ['saucepan', 'butter', 'stir', 'flour', 'milk'],
   ['cheddar', 'cheese', 'stir'],
   ['Combine', 'macaroni', 'transfer', 'dish', 'top', 'breadcrumbs']],
  'Instruction': [['Cook'], [], [], []],
  'Step': [' Cook 8 oz of macaroni.',
   'In a saucepan, melt 2 tbsp of butter, stir in 2 tbsp of flour, gradually add 2 cups of milk, stirring until thickened.',
   'Add 2 cups of shredded cheddar cheese, stir until melted.',
   'Combine with macaroni, transfer to a baking dish, top with breadcrumbs, and bake at 350°F for 20 minutes.']},
 'Chicken Alfredo Pasta': {'Amount': [['8'], ['1'], ['1'], []],
  'Measure Type': [['oz'], ['pan', 'lb'], ['cup'], []],
  'Ingredient': [['fettuccine', 'drain'],
   ['chicken', 'breast'],
   ['sauce', 'chicken', 'heat'],
   ['Toss', 'pasta', 'cheese']],
  'Instruction': [['Cook'], [], ['Alfredo'], ['Parmesan']],
  'Step': [' Cook 8 oz of fettuccine, drain.',
   'In a pan, cook 1 lb of sliced chicken breast until golden.',
   'Add 1 cup of Alfredo sauce to the chicken, heat through.',
   'Toss with pasta, garnish with grated Parmesan cheese.']},
 'Mushroom Risotto': {'Amount': [['1', '1/2'], ['1'], ['4'], []],
  'Measure Type': [['cup', 'cup'], ['cup'], ['cups'], []],
  'Ingredient': [['saucepan', 'mushrooms', 'onion', 'butter'],
   ['rice', 'cook', 'translucent'],
   ['broth', 'rice', 'tender'],
   ['cheese', 'drizzle', 'oil']],
  'Instruction': [[], ['Stir', 'Arborio'], [], ['Parmesan']],
  'Step': [' In a saucepan, sauté 1 cup of chopped mushrooms and 1/2 cup of chopped onion in butter until soft.',
   'Stir in 1 cup of Arborio rice, cook until translucent.',
   'Gradually add 4 cups of vegetable broth, stirring constantly, until the rice is creamy and tender.',
   'Finish with grated Parmesan cheese and a drizzle of truffle oil.']},
 'Tomato Bruschetta': {'Amount': [['2', '1/4', '2', '1', '1'], []],
  'Measure Type': [['cup', 'tbsp', 'tsp'], []],
  'Ingredient': [['tomatoes',
    'mix',
    'basil',
    'cloves',
    'oil',
    'vinegar',
    'salt',
    'pepper',
    'taste'],
   ['slices', 'baguette']],
  'Instruction': [['Dice'], ['Spoon']],
  'Step': [' Dice 2 large tomatoes and mix with 1/4 cup of finely chopped basil, 2 minced garlic cloves, 1 tbsp olive oil, 1 tsp balsamic vinegar, salt, and pepper to taste.',
   'Spoon onto slices of toasted baguette.']},
 'Grilled Salmon': {'Amount': [['4', '30'], []],
  'Measure Type': [['minutes'], ['minutes']],
  'Ingredient': [['salmon',
    'fillets',
    'mixture',
    'oil',
    'lemon',
    'juice',
    'salt',
    'pepper'],
   ['medium', 'heat', 'side', 'doneness']],
  'Instruction': [['Marinate'], ['Grill']],
  'Step': [' Marinate 4 salmon fillets in a mixture of olive oil, lemon juice, minced garlic, salt, and pepper for at least 30 minutes.',
   'Grill over medium heat for 3-4 minutes per side or until desired doneness.']},
 'Chicken Parmesan': {'Amount': [['4'], [], [], ['375°F', '20']],
  'Measure Type': [[], [], [], ['minutes']],
  'Ingredient': [['Pound', 'chicken', 'breasts'],
   ['beaten', 'eggs', 'mixture', 'breadcrumbs'],
   ['place', 'dish', 'cover', 'sauce', 'mozzarella', 'cheese'],
   []],
  'Instruction': [[], ['Dip', 'Parmesan'], ['Fry'], ['Bake']],
  'Step': [' Pound 4 chicken breasts to even thickness.',
   'Dip in beaten eggs, then in a mixture of breadcrumbs and grated Parmesan.',
   'Fry until golden, place in a baking dish, cover with marinara sauce and mozzarella cheese.',
   'Bake at 375°F for 20 minutes.']},
 'Vegetable Quiche': {'Amount': [['375°F', '10'],
   ['1'],
   ['4', '1'],
   ['1/2'],
   ['375°F', '35']],
  'Measure Type': [['minutes'], ['cup'], ['cup'], ['cup'], ['minutes']],
  'Ingredient': [['pie', 'crust'],
   ['spinach', 'mushrooms', 'onions'],
   ['vegetables', 'crust', 'mixture', 'beaten', 'eggs', 'cream'],
   ['cheese'],
   []],
  'Instruction': [[], ['Sauté'], [], [], ['Bake']],
  'Step': [' Pre-bake a pie crust at 375°F for 10 minutes.',
   'Sauté 1 cup each of chopped spinach, mushrooms, and onions until soft.',
   'Spread the vegetables in the crust, pour over a mixture of 4 beaten eggs and 1 cup of cream.',
   'Top with 1/2 cup of shredded cheese.',
   'Bake at 375°F for 35 minutes.']}}

In [73]:
for i in final:
    print(i)
    display(pd.DataFrame(final[i]))
    print("\n"*3)

Chocolate Chip Cookies

,Amount,Measure Type,Ingredient,Instruction,Step
0,"[2, 1, 1, 1]","[cups, cup, cup, tsp, pinch]","[flour, sugar, sugar, soda, salt]",[Combine],"Combine 2 cups of flour, 1 cup of sugar, 1 cu..."
1,"[1, 2, 2]","[cup, tsp]","[Cream, butter, eggs, vanilla, extract]",[],"Cream together with 1 cup of softened butter, ..."
2,[2],[cups],"[chocolate, chips]",[Fold],Fold in 2 cups of chocolate chips.
3,"[350°F, 10]","[spoonfuls, minutes]","[sheet, bake, brown]",[Drop],Drop spoonfuls on a baking sheet and bake at 3...

Vegetable Stir Fry

,Amount,Measure Type,Ingredient,Instruction,Step
0,"[2, 1]","[tbsp, pan]","[oil, inch, ginger, vegetables, broccoli, carr...",[Heat],"Heat 2 tbsp of olive oil in a pan, add minced..."
1,[],[],[tender],[Stir-fry],Stir-fry until tender.
2,[2],[tbsp],"[soy, sauce, rice, noodles]",[],Add 2 tbsp of soy sauce and serve hot with ric...

Banana Bread

,Amount,Measure Type,Ingredient,Instruction,Step
0,"[3, 1/3]",[cup],"[ripe, bananas, mix, butter]",[Mash],"Mash 3 ripe bananas, mix with 1/3 cup melted ..."
1,"[1, 1, 1]","[cup, tsp]","[sugar, beaten, egg, vanilla, extract]",[Stir],"Stir in 1 cup of sugar, 1 beaten egg, and 1 ts..."
2,[1],"[tsp, pinch]","[soda, salt]",[Mix],Mix in 1 tsp of baking soda and a pinch of salt.
3,[1.5],[cups],[flour],[],Gently fold in 1.5 cups of flour.
4,"[350°F, 1]",[pan],"[bake, hour]",[Pour],Pour into a loaf pan and bake at 350°F for 1 h...

Chicken Curry

,Amount,Measure Type,Ingredient,Instruction,Step
0,"[1, 2, 1]","[tbsp, pan]","[onion, cloves, ginger, oil]",[Sauté],"Sauté 1 chopped onion, 2 minced garlic cloves..."
1,[1],[lb],"[chicken, breast, cook]",[],"Add 1 lb of diced chicken breast, cook until b..."
2,"[2, 1, 1]","[tsp, cup]","[curry, powder, tomatoes, coconut, milk]",[Stir],"Stir in 2 tsp of curry powder, add 1 can of cr..."
3,[20],[minutes],[],[Simmer],Simmer for 20 minutes.
4,[],[],"[Serve, rice]",[],Serve with rice.

Spaghetti Carbonara

,Amount,Measure Type,Ingredient,Instruction,Step
0,[8],[oz],"[spaghetti, package, instructions]",[Cook],Cook 8 oz of spaghetti according to package i...
1,[4],[pan],"[slices, bacon, crisp]",[],"In a separate pan, cook 4 slices of chopped ba..."
2,"[2, 1/2]",[cup],"[eggs, cheese, mix, spaghetti, bacon, season, ...","[Beat, Parmesan]",Beat 2 eggs and 1/2 cup of grated Parmesan che...

Caesar Salad

,Amount,Measure Type,Ingredient,Instruction,Step
0,[4],[cups],"[romaine, lettuce]",[Caesar],Toss 4 cups of chopped romaine lettuce with C...
1,[],[],"[croutons, sprinkle, cheese]","[Add, Parmesan]",Add croutons and sprinkle with grated Parmesan...
2,[],[],"[protein, top, chicken, strips]",[],"For added protein, top with grilled chicken st..."

Beef Tacos

,Amount,Measure Type,Ingredient,Instruction,Step
0,[1],[lb],"[ground, beef, taco, seasoning]",[Cook],Cook 1 lb of ground beef with taco seasoning.
1,[],[],"[tortillas, toppings, lettuce, tomatoes, chees...",[Serve],"Serve in tortillas with toppings like lettuce,..."

Margarita Pizza

,Amount,Measure Type,Ingredient,Instruction,Step
0,[8],[oz],"[tomato, sauce, round, pizza, dough, sprinkle,...",[Spread],Spread tomato sauce over a round of pizza dou...
1,[475°F],[minutes],[],[Bake],Bake at 475°F for 10-12 minutes.
2,[],[],"[oil, serving]",[Drizzle],Drizzle with olive oil before serving.

Lemonade

,Amount,Measure Type,Ingredient,Instruction,Step
0,"[1, 1, 4]","[cup, cup, cups]","[juice, sugar, water]",[Mix],Mix 1 cup of lemon juice with 1 cup of sugar ...
1,[],[],"[sweetness, sugar, water]",[Adjust],Adjust sweetness by adding more sugar or water...
2,[],[],[ice],[Serve],Serve over ice.

French Toast

,Amount,Measure Type,Ingredient,Instruction,Step
0,"[2, 1/2, 1]","[cup, pinch, tsp]","[eggs, milk, cinnamon, vanilla, extract]",[Whisk],"Whisk together 2 eggs, 1/2 cup of milk, a pin..."
1,[],[pan],"[slices, bread, mixture, fry, sides]",[Dip],"Dip slices of bread into the mixture, fry in a..."
2,[],[syrup],[Serve],[],Serve with maple syrup.

Guacamole

,Amount,Measure Type,Ingredient,Instruction,Step
0,"[2, 1, 1/4, 1, 1]",[cup],"[ripe, avocados, bowl, mix, juice, lime, salt,...",[Mash],"Mash 2 ripe avocados in a bowl, mix with the ..."

Pumpkin Soup

,Amount,Measure Type,Ingredient,Instruction,Step
0,"[1, 2]",[],"[onion, cloves, pot, oil]",[Sauté],Sauté 1 chopped onion and 2 minced garlic clo...
1,"[2, 4, 20]","[cups, cups, minutes]","[puree, stock, simmer]",[],"Add 2 cups of pumpkin puree, 4 cups of vegetab..."
2,[1/2],[cup],"[stir, cream, season, salt, pepper]","[Blend, smooth]","Blend until smooth, stir in 1/2 cup of cream, ..."

Raspberry Smoothie

,Amount,Measure Type,Ingredient,Instruction,Step
0,"[1, 1, 1/2, 1]","[cup, cup, tbsp]","[raspberries, banana, yogurt, honey, handful, ...",[Blend],"Blend 1 cup of raspberries, 1 sliced banana, ..."

Macaroni and Cheese

,Amount,Measure Type,Ingredient,Instruction,Step
0,[8],[oz],[macaroni],[Cook],Cook 8 oz of macaroni.
1,"[2, 2, 2]","[tbsp, tbsp, cups]","[saucepan, butter, stir, flour, milk]",[],"In a saucepan, melt 2 tbsp of butter, stir in ..."
2,[2],[cups],"[cheddar, cheese, stir]",[],"Add 2 cups of shredded cheddar cheese, stir un..."
3,"[350°F, 20]",[minutes],"[Combine, macaroni, transfer, dish, top, bread...",[],"Combine with macaroni, transfer to a baking di..."

Chicken Alfredo Pasta

,Amount,Measure Type,Ingredient,Instruction,Step
0,[8],[oz],"[fettuccine, drain]",[Cook],"Cook 8 oz of fettuccine, drain."
1,[1],"[pan, lb]","[chicken, breast]",[],"In a pan, cook 1 lb of sliced chicken breast u..."
2,[1],[cup],"[sauce, chicken, heat]",[Alfredo],"Add 1 cup of Alfredo sauce to the chicken, hea..."
3,[],[],"[Toss, pasta, cheese]",[Parmesan],"Toss with pasta, garnish with grated Parmesan ..."

Mushroom Risotto

,Amount,Measure Type,Ingredient,Instruction,Step
0,"[1, 1/2]","[cup, cup]","[saucepan, mushrooms, onion, butter]",[],"In a saucepan, sauté 1 cup of chopped mushroo..."
1,[1],[cup],"[rice, cook, translucent]","[Stir, Arborio]","Stir in 1 cup of Arborio rice, cook until tran..."
2,[4],[cups],"[broth, rice, tender]",[],"Gradually add 4 cups of vegetable broth, stirr..."
3,[],[],"[cheese, drizzle, oil]",[Parmesan],Finish with grated Parmesan cheese and a drizz...

Tomato Bruschetta

,Amount,Measure Type,Ingredient,Instruction,Step
0,"[2, 1/4, 2, 1, 1]","[cup, tbsp, tsp]","[tomatoes, mix, basil, cloves, oil, vinegar, s...",[Dice],Dice 2 large tomatoes and mix with 1/4 cup of...
1,[],[],"[slices, baguette]",[Spoon],Spoon onto slices of toasted baguette.

Grilled Salmon

,Amount,Measure Type,Ingredient,Instruction,Step
0,"[4, 30]",[minutes],"[salmon, fillets, mixture, oil, lemon, juice, ...",[Marinate],Marinate 4 salmon fillets in a mixture of oli...
1,[],[minutes],"[medium, heat, side, doneness]",[Grill],Grill over medium heat for 3-4 minutes per sid...

Chicken Parmesan

,Amount,Measure Type,Ingredient,Instruction,Step
0,[4],[],"[Pound, chicken, breasts]",[],Pound 4 chicken breasts to even thickness.
1,[],[],"[beaten, eggs, mixture, breadcrumbs]","[Dip, Parmesan]","Dip in beaten eggs, then in a mixture of bread..."
2,[],[],"[place, dish, cover, sauce, mozzarella, cheese]",[Fry],"Fry until golden, place in a baking dish, cove..."
3,"[375°F, 20]",[minutes],[],[Bake],Bake at 375°F for 20 minutes.

Vegetable Quiche

,Amount,Measure Type,Ingredient,Instruction,Step
0,"[375°F, 10]",[minutes],"[pie, crust]",[],Pre-bake a pie crust at 375°F for 10 minutes.
1,[1],[cup],"[spinach, mushrooms, onions]",[Sauté],"Sauté 1 cup each of chopped spinach, mushrooms..."
2,"[4, 1]",[cup],"[vegetables, crust, mixture, beaten, eggs, cream]",[],"Spread the vegetables in the crust, pour over ..."
3,[1/2],[cup],[cheese],[],Top with 1/2 cup of shredded cheese.
4,"[375°F, 35]",[minutes],[],[Bake],Bake at 375°F for 35 minutes.